### ISSUE TITLE
command 'extension.createConfigFile' not found

### ISSUE THREAD

**Issue by heyMP** [oslabs-beta/GraphQuill#26]
I installed from the marketplace.  Ran createConfigFile and got the following error:

`command 'extension.createConfigFile' not found`

![Screen Shot 2019-11-21 at 4 20 14 PM](https://user-images.githubusercontent.com/3428964/69377777-f38f0000-0c7a-11ea-99fa-1e8318edba89.png)

**Comment by alexchao26** [comment]
I'm looking into it!

**Comment by alexchao26** [comment]
@heyMP Thanks for checking out our extension! 

Can you try restarting VS Code and then opening a file from within a GraphQL folder directory. With a file open could you then run the Create Config File command and see if the results change?

**Comment by heyMP** [comment]
Yep that worked.  Thanks!

**Comment by alexchao26** [comment]
Awesome, I will go back and update error messaging to indicate that to future users. Thanks, this feedback is exactly what we're looking for!
