### ISSUE TITLE
Connect to existing server?

### ISSUE THREAD

**Issue by jamestenglish** [oslabs-beta/GraphQuill#30]
I looked through the documentation and it doesn't seem likely, but I thought I'd ask. Can this connect to an existing/remote server or can it only be used with a server it starts?

**Comment by alexchao26** [comment]
Hi @jamestenglish , thanks for checking out our extension.
To answer your question shortly, no GraphQuill does not NEED to start the server (there are actually situations where we prefer the user to start their own server).

The slightly longer answer is that at the current moment, the code is such that it queries a localhost port, so the server does need to be running on a port on your machine.
Compatibility for third party API's (URL's besides localhost) is a proposed feature which we would like to add to improve GraphQuill's utility, but we do not have a timeline for its completion.

**Comment by alexchao26** [comment]
@jamestenglish 
We've added compatibility for 3rd party APIs today in PR#32. If you provide a url starting with 'http' in the config file it will send queries to that url. Hope that helps!

**Comment by gilesbutler** [comment]
Hey @alexchao26, cool extension! Will this work with AWS AppSync endpoints that require authentication?

**Comment by alexchao26** [comment]
Thanks @gilesbutler ! Unfortunately we don't support authentication services such as JWTs or Auth tokens. I'm not that familiar with AppSync so I can't give you a solid answer.
If you need to send some kind of auth token along with every GraphQL query, GraphQuill won't be able to support it. Although this is probably unlikely, if there is a way to spin up your server and export a local port to the server that doesn't require tokens or authentication with every request, then GraphQuill could work!

**Comment by gilesbutler** [comment]
Thanks @alexchao26. Yeah unfortunately AppSync is a hosted service and our endpoints all require auth. All good, just thought I'd check 👍
